### ISSUE TITLE
Oracle Model Insert with Sequence

### ISSUE THREAD

**Issue by firefoxNX** [featurist/sworm#16]
Is it possible to use db.model.save() method to insert to a table using Oracle sequence?

**Comment by refractalize** [comment]
Do you mean an [oracle sequence](https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_6015.htm) as in `create sequence`?

That should work automatically, you just need to create and save an entity without specifying an ID.

Unless I'm not understanding your question correctly?

**Comment by firefoxNX** [comment]
@refractalize how does db.model.save() work when a table has a sequence? does it generate insert statement with mySeq.nexVal? for ex. `insert into emp (empno) values(mySeq.nextVal);`

```
save() {
    return new Promise((resolve) => {
      const someTbl = db.model({ table: "some_table", id: "some_ID", idType: 2001 });
      const modelObj = someTbl({
        some_column: this.someColumn,
        ...
        
      });
      if (!this.id) {
        modelObj.SOME_ID = "how should i provide seqname.next_val here?";
        ...
      }
      modelObj.save().then((saved) => { return resolve(saved); });
    });
  }
```

**Comment by refractalize** [comment]
this isn't really supported in sworm since most databases have support for default values, including auto-generated IDs. Oracle allows [default values from sequences](https://oracle-base.com/articles/12c/default-values-for-table-columns-enhancements-12cr1) from 12c, so that would be worth looking at if you're on that version.

If not however, you can use a trigger:

```sql
create table my_table (
  my_id varchar(10) primary key,
  ...
);

create sequence my_table_seq;

create or replace trigger my_table_id
  before insert on my_table
  for each row
begin
  select my_table_seq.nextval into :new.my_id from dual;
end;
```

I'm slightly reluctant to add support for this to sworm as Oracle is really the odd one out as far as databases go on this subject, and recent versions are fine anyway.

**Comment by firefoxNX** [comment]
Make sense. We are on 11g so will either use a db trigger as you suggested or do an extra select query before doing save call. Thanks @refractalize for making sworm!

**Comment by refractalize** [comment]
Sworm now has `unescape()`, so you can refer to `my_sequence.nextval` when inserting or updating. See docs here https://github.com/featurist/sworm#unescaping
