### ISSUE TITLE
DB2, NoSQL?

### ISSUE THREAD

**Issue by kiritbasu** [featurist/sworm#23]
Hi, Any plans to support DB2 or any of the NoSQL systems (Mongo etc)?

**Comment by refractalize** [comment]
Hi @kiritbasu, I haven't been formally introduced to DB2 yet, so it hadn't occurred to me to add support for it. I'm willing to help somebody put together a PR to make that happen mind you.

For NoSQL systems, the usefulness of sworm diminishes quite a bit, since NoSQLs tend to support deep relational structures out of the box - so writing large graphs isn't normally a problem. If you can point out a use-case for a NoSQL system, then I'll consider it.

**Comment by kiritbasu** [comment]
I was trying to avoid doing the work on DB2 hence the question. ;-)

per nosql -  I'm basically using this to generate a bunch of test data on all of these DB's, so for me just a single unified way to do so would be most convenient.

**Comment by refractalize** [comment]
the issue with NoSQL is that you'll likely be using a schema that's very different in structure to that you'd find in SQL, so, even if sworm _did_ do NoSQL, using the same code across SQL and NoSQL databases is probably not what you want anyway.

So.. in short, unless there's a PR for NoSQL with compelling use-cases I don't think it's going to happen. DB2 makes more sense since it's regular SQL, but again I can't see support arriving without a PR from somebody who knows what they're doing with DB2.

Sorry!
